# Generated by Django 5.0.1 on 2024-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pno', models.CharField(max_length=10)),
                ('ad', models.ImageField(upload_to='media/')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
