# Generated by Django 5.0.1 on 2024-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
