# Generated by Django 5.0.1 on 2024-02-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_car_rejection_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dealer_reg',
            new_name='customer',
        ),
        migrations.RenameModel(
            old_name='register',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ad',
            new_name='dl',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dl',
            new_name='ad',
        ),
    ]
