# Generated by Django 5.0.1 on 2024-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_dealer_reg_customer_rename_register_dealer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripRequest',
            new_name='Booking',
        ),
        migrations.AddField(
            model_name='car',
            name='regno',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
