# Generated by Django 5.0.1 on 2024-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_triprequest_booking_car_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='regno',
            field=models.CharField(max_length=20),
        ),
    ]
