# Generated by Django 5.0.1 on 2024-02-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_car_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pno',
        ),
        migrations.AddField(
            model_name='booking',
            name='regno',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
