# Generated by Django 5.0.1 on 2024-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_booking_pno_booking_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='regno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
