# Generated by Django 5.0.1 on 2024-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_pickup_time_booking_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
