# Generated by Django 5.0.1 on 2024-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_booking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
