# Generated by Django 5.0.1 on 2024-02-22 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='app1.dealer'),
            preserve_default=False,
        ),
    ]
